### PR TITLE
Unity version and packages update

### PR DESCRIPTION
**Pull request by SurajSSingh**
## Changes
1. Update Unity to 2021.3.41f1
2. Update existing packages
3. Add Acknowledgement file (for 3rd part assets and packages)
4. Add the following new packages:

    - [Recorder](https://docs.unity3d.com/Packages/com.unity.recorder@3.0/manual/index.html)
    - [Fast Script Reload](https://openupm.com/packages/com.handzlikchris.fastscriptreload/)
    - [SuperUnityBuild BuildTool](https://openupm.com/packages/com.github.superunitybuild.buildtool/)
    - [SuperUnityBuild BuildAction](https://openupm.com/packages/com.github.superunitybuild.buildactions/)
    - [Editor Toolbox](https://openupm.com/packages/com.browar.editor-toolbox/)
    - [Better Attributes](https://openupm.com/packages/com.uurha.betterattributes/)
    - [DOTween](https://dotween.demigiant.com/)
    - [Animation Sequencer](https://openupm.com/packages/com.brunomikoski.animationsequencer/)
    - [PlayerPrefsEditor](https://openupm.com/packages/com.bgtools.playerprefseditor/)
    - [Compilation Visualizer](https://openupm.com/packages/com.needle.compilation-visualizer)

### Known Bugs/Issues
None found yet.

## Testing Scene and Script
Just open Unity and test that everything is stable. Programmers may also want to test C# project with access to new packages.

## Issue ticket number/link
None

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] Make sure I am merging my features into the `develop` branch
- [X] I have notified the other members of the programming team that my task is ready to review

### CODE REVIEW

**Review by KallenXCC — APPROVED** [review]
Tested on 2021.3.41f1, packages and workspace seems stable. Should be good to merge when you're ready

**Comment by SurajSSingh** [comment]
Thank @KallenXCC, I'll wait for two more approvals before merging it in

**Review by rwchaneyjr — APPROVED** [review]

**Comment by SurajSSingh** [comment]
Thanks @rwchaneyjr, I'll wait for one more approval before merging

**Review by LouieMarcou — APPROVED** [review]

**Comment by SurajSSingh** [comment]
Thanks @LouieMarcou, I will merge in these changes

**Pull request merged**
